
    version: '3'
    services:
      ngi:
        image: nginx:latest
        ports:
          - "800:80"
        volumes:
          - ./webser:/etc/nginx/conf.d
          - ./wwww:/var/www
          - ./journal/wserv:/var/log/nginx
        links:
          - piha
      piha:
        build: ./constr/hyprep
        extra_hosts:
          host.docker.internal: host-gateway
        # ports:
        #   - "3000:8000"
        volumes:
          - ./wwww:/var/www
          - ./journal/xdeb:/var/logs/xdebug
          ## - ./phconf:/etc/php/8.1/fpm/conf.d
        links:
          - masha
      masha:
        image: mariadb:10.11.2
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: vehshop
          MYSQL_USER: app
          MYSQL_PASSWORD: demo
        volumes:
          - ./databa:/var/lib/mysql
        ports:
          - "33060:3306"
